require('dotenv').config();
const express=require('express'); const cors=require('cors'); const path=require('path'); const WebSocket=require('ws');
const app=express(); app.use(cors()); app.use(express.json()); app.use(express.static(path.join(__dirname,'frontend')));
const SPOT='https://api.binance.com', FUT='https://fapi.binance.com', PORT=process.env.PORT||3000, HOST=process.env.HOST||'0.0.0.0';
const cache={etf:{t:0,data:null},macro:{t:0,data:null},news:{t:0,data:[]},flow:{t:0,data:null}}; const CACHE={etf:15*60e3,macro:30e3,news:2*60e3,flow:8e3};
const oiSnapshots=[], liqEvents=[], largeTrades=[]; let wsState={connected:false,lastMessage:0,reconnects:0};
async function getJson(base,url,opts={}){const r=await fetch((base||'')+url,{headers:{Accept:'application/json','User-Agent':'BTC-Scalping-V2'},...opts}); const txt=await r.text(); let j; try{j=JSON.parse(txt)}catch{throw Error(`Invalid JSON HTTP ${r.status}`)} if(!r.ok)throw Error(`HTTP ${r.status}`); return j}
async function getText(url){const r=await fetch(url,{headers:{Accept:'text/html,application/xml,text/xml','User-Agent':'BTC-Scalping-V2'}}); const t=await r.text(); if(!r.ok)throw Error(`HTTP ${r.status}`); return t}
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function ema(a,n){if(a.length<n)return null; let e=avg(a.slice(0,n)),k=2/(n+1); for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k); return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=1;i<=n;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){let d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al===0?100:100-100/(1+ag/al)}
function vwap(ks){let pv=0,v=0;for(const k of ks){let h=+k[2],l=+k[3],c=+k[4],vol=+k[5];pv+=(h+l+c)/3*vol;v+=vol}return v?pv/v:null}
function atr(ks,n=14){if(ks.length<n+1)return null;const tr=[];for(let i=1;i<ks.length;i++){const h=+ks[i][2],l=+ks[i][3],pc=+ks[i-1][4];tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)))}return avg(tr.slice(-n))}
function technical(ks){const c=ks.map(k=>+k[4]),vol=ks.map(k=>+k[5]),price=c.at(-1),e20=ema(c,20),e50=ema(c,50),rv=rsi(c),vw=vwap(ks),a=atr(ks),av=avg(vol.slice(-20));const vr=av?vol.at(-1)/av:null;const trend=price>e20&&e20>e50?'BULLISH':price<e20&&e20<e50?'BEARISH':'MIXED';let score=50;if(price>e20)score+=10;else score-=10;if(e20>e50)score+=10;else score-=10;if(price>vw)score+=10;else score-=10;if(rv>=50&&rv<=70)score+=10;else if(rv<40)score-=10;if(vr>1.2)score+=trend==='BULLISH'?10:trend==='BEARISH'?-10:0;return {price,rsi:rv,vwap:vw,ema20:e20,ema50:e50,volumeRatio:vr,trend,vwapBias:price>vw?'ABOVE VWAP':'BELOW VWAP',atr:a,score:Math.max(0,Math.min(100,Math.round(score))),high:Math.max(...ks.slice(-20).map(k=>+k[2])),low:Math.min(...ks.slice(-20).map(k=>+k[3]))}}
async function tfTech(i){return technical(await getJson(SPOT,`/api/v3/klines?symbol=BTCUSDT&interval=${i}&limit=180`))}
async function currentOI(){const [oi,px]=await Promise.all([getJson(FUT,'/fapi/v1/openInterest?symbol=BTCUSDT'),getJson(FUT,'/fapi/v1/premiumIndex?symbol=BTCUSDT')]);const btc=+oi.openInterest,mark=+px.markPrice;return {btc,usd:btc*mark,markPrice:mark}}
async function funding(){const j=await getJson(FUT,'/fapi/v1/premiumIndex?symbol=BTCUSDT');return {rate:+j.lastFundingRate,markPrice:+j.markPrice,nextFundingTime:j.nextFundingTime}}
async function longShort(){try{const j=await getJson(FUT,'/futures/data/globalLongShortAccountRatio?symbol=BTCUSDT&period=5m&limit=1');const x=j?.[0];return x?{long:+x.longAccount,short:+x.shortAccount,ratio:+x.longShortRatio}:null}catch{return null}}
async function fearGreed(){try{return (await getJson('https://api.alternative.me','/fng/?limit=1')).data?.[0]||null}catch{return null}}
function prune(){const n=Date.now();while(oiSnapshots[0]&&n-oiSnapshots[0].t>25*3600e3)oiSnapshots.shift();while(liqEvents[0]&&n-liqEvents[0].t>3600e3)liqEvents.shift();while(largeTrades[0]&&n-largeTrades[0].t>15*60e3)largeTrades.shift()}
function snapshotOI(v){oiSnapshots.push({t:Date.now(),v});prune()}; function changeSince(ms){const n=Date.now(),last=oiSnapshots.at(-1);if(!last)return null;for(let i=oiSnapshots.length-1;i>=0;i--)if(n-oiSnapshots[i].t>=ms)return oiSnapshots[i].v?((last.v/oiSnapshots[i].v)-1)*100:null;return null}
function addLiq(side,usd){liqEvents.push({t:Date.now(),side,usd});prune()}; function addLarge(side,usd){if(usd>=100000)largeTrades.push({t:Date.now(),side,usd});prune()}
function liqSummary(){prune();let lo=0,sh=0;for(const x of liqEvents)x.side==='LONG'?lo+=x.usd:sh+=x.usd;return {total1h:lo+sh,long1h:lo,short1h:sh,bias:lo+sh===0?'NO RECENT LIQUIDATION':sh>lo?'SHORT LIQUIDATION HEAVY':'LONG LIQUIDATION HEAVY',events:liqEvents.length}}
function largeSummary(){prune();let b=0,s=0;for(const x of largeTrades)x.side==='BUY'?b+=x.usd:s+=x.usd;return {count:largeTrades.length,buyUsd:b,sellUsd:s,netUsd:b-s,bias:largeTrades.length?(b>s?'BUY PRESSURE':'SELL PRESSURE'):'NO LARGE-TRADE DATA',note:'Binance aggregate-trade proxy; not wallet-level institutional flow'}}
function strip(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function num(s){s=strip(s);if(!s||s==='-'||s==='—')return null;let neg=/^\(.*\)$/.test(s);let n=Number(s.replace(/[(),$]/g,''));return Number.isFinite(n)?(neg?-n:n):null}
async function getETF(){if(cache.etf.data&&Date.now()-cache.etf.t<CACHE.etf)return cache.etf.data;try{const html=await getText('https://farside.co.uk/btc/');const rows=[...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(x=>x[1]),a=[];for(const row of rows){const c=[...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>strip(x[1]));if(c.length>=3&&/^\d{1,2}\s+[A-Za-z]{3}\s+\d{4}$/.test(c[0])){const vals=c.slice(1).map(num),total=vals.at(-1);if(Number.isFinite(total))a.push({date:c[0],total})}}const x=a.at(-1);if(!x)throw Error('ETF table unavailable');cache.etf={t:Date.now(),data:{...x,source:'Farside Investors'}};return cache.etf.data}catch{return cache.etf.data||null}}
async function yahooSeries(symbol){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=5m`;const j=await getJson('',u),r=j?.chart?.result?.[0],q=r?.indicators?.quote?.[0],c=(q?.close||[]).filter(Number.isFinite);return {last:c.at(-1)??null,old:c.length>=7?c.at(-7):null,change:c.length>=7?((c.at(-1)/c.at(-7))-1)*100:null}}
async function getMarkets(){const symbols={DXY:'DX-Y.NYB',NASDAQ:'^IXIC',SP500:'^GSPC',DOW:'^DJI',VIX:'^VIX',FTSE:'^FTSE',NIKKEI:'^N225',SHANGHAI:'000001.SS',NIFTY:'^NSEI',SENSEX:'^BSESN'};try{const out={};await Promise.all(Object.entries(symbols).map(async([k,s])=>out[k]=await yahooSeries(s)));cache.macro={t:Date.now(),data:out};return out}catch{return cache.macro.data||null}}
async function getNews(){if(cache.news.data.length&&Date.now()-cache.news.t<CACHE.news)return cache.news.data;const feeds=[['CoinDesk','https://www.coindesk.com/arc/outboundfeeds/rss/'],['Cointelegraph','https://cointelegraph.com/rss']];const all=[];for(const [source,url] of feeds){try{const xml=await getText(url);for(const m of [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,6)){const b=m[1],title=strip((b.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]),link=strip((b.match(/<link[^>]*>([\s\S]*?)<\/link>/i)||[])[1]);if(title)all.push({source,title,link})}}catch{}}cache.news={t:Date.now(),data:all.slice(0,12)};return cache.news.data}

async function getFlowStats(){if(cache.flow.data&&Date.now()-cache.flow.t<CACHE.flow)return cache.flow.data;const map={'1m':'1m','5m':'5m','10m':'10m','30m':'30m','1H':'1h','1D':'1d'},out={};await Promise.all(Object.entries(map).map(async([tf,i])=>{try{const k=await getJson(SPOT,`/api/v3/klines?symbol=BTCUSDT&interval=${i}&limit=3`);const vols=k.map(x=>+x[7]),last=vols.at(-1),prev=vols.at(-2);out[tf]={volume:last,volumeChange:prev?((last/prev)-1)*100:null,priceChange:+k.at(-1)[4]-+k.at(-1)[1]} }catch{out[tf]={volume:null,volumeChange:null}}}));cache.flow={t:Date.now(),data:out};return out}

function sessionStatus(){const now=new Date(),parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now);const mins=+parts.find(x=>x.type==='hour').value*60 + +parts.find(x=>x.type==='minute').value;const us=mins>=19*60+0||mins<1*60+30;const uk=mins>=13*60+30&&mins<22*60;const india=mins>=9*60+15&&mins<15*60+30;const china=mins>=7*60&&mins<13*60+30;return {India:india?'OPEN':'CLOSED',USA:us?'OPEN':'CLOSED',UK:uk?'OPEN':'CLOSED',China:china?'OPEN':'CLOSED',note:'Regular-session clock; holidays may differ'}}
function signal(t5,t15,oi5,fund,fg,liq,large,etf,markets){const f={};f.price=Math.round((t5.score+t15.score)/2);f.rsi=t5.rsi>=50&&t5.rsi<=70?80:t5.rsi<40?25:t5.rsi>75?35:55;f.ema=clamp(50+(t5.price>t5.ema20?15:-15)+(t5.ema20>t5.ema50?20:-20)+(t5.price>t5.vwap?15:-15));f.volume=t5.volumeRatio==null?null:clamp(50+(t5.volumeRatio-1)*40*(t5.trend==='BEARISH'?-1:1));f.oi=oi5==null?null:clamp(50+oi5*20);f.funding=Number.isFinite(fund)?clamp(50-fund*50000):null;f.liq=liq.total1h?clamp(100*liq.short1h/liq.total1h):50;f.large=large.count?clamp(50+Math.sign(large.netUsd)*Math.min(35,Math.abs(large.netUsd)/1e6*35)):null;f.etf=etf?.total==null?null:clamp(50+Math.sign(etf.total)*Math.min(40,Math.abs(etf.total)/100*10));let macro=50;if(markets?.DXY?.change!=null)macro+=markets.DXY.change<0?8:-8;if(markets?.NASDAQ?.change!=null)macro+=markets.NASDAQ.change>0?8:-8;f.macro=clamp(macro);f.fg=fg==null?null:+fg;const w={price:15,rsi:10,ema:10,volume:10,oi:15,funding:5,liq:10,large:10,etf:5,macro:5,fg:5};let total=0,wt=0;for(const k in f)if(Number.isFinite(f[k])){total+=f[k]*w[k];wt+=w[k]}const score=wt?Math.round(total/wt):50,coverage=Math.round(wt),dir=score>=72?'LONG':score<=28?'SHORT':'WAIT',range=Math.max(t5.atr||0,t5.price*.0015,Math.abs(t5.price-t5.ema20)*1.2);const entry=t5.price,sl=dir==='LONG'?entry-range:dir==='SHORT'?entry+range:null,t1=dir==='LONG'?entry+range*1.5:dir==='SHORT'?entry-range*1.5:null,t2=dir==='LONG'?entry+range*2.2:dir==='SHORT'?entry-range*2.2:null;const confidence=Math.min(95,Math.round(45+coverage*.45+Math.abs(score-50)*.35));const reasons=[];if(t5.price>t5.vwap)reasons.push('Price above VWAP');else reasons.push('Price below VWAP');if(t5.ema20>t5.ema50)reasons.push('EMA20 > EMA50');else reasons.push('EMA20 < EMA50');if(t5.rsi<40)reasons.push('RSI weak');else if(t5.rsi>70)reasons.push('RSI stretched');if(oi5!=null)reasons.push(`OI ${oi5>=0?'+':''}${oi5.toFixed(2)}%/5m`);if(etf?.total!=null)reasons.push(`ETF ${etf.total>=0?'+':''}${etf.total.toFixed(1)}m`);return {score,coverage,confidence,direction:dir,label:dir==='LONG'?'🟢 STRONG/LONG':dir==='SHORT'?'🔴 STRONG/SHORT':'🟡 WAIT',entry:dir==='WAIT'?null:entry,sl,target1:t1,target2:t2,holding:dir==='WAIT'?'WAIT':'5–30 min',factors:f,reasons,decision:dir==='WAIT'?'No trade: confirmation is insufficient.':'Trade only with confirmation; this is decision support, not guaranteed profit.'}}
function clamp(x){return Math.max(0,Math.min(100,x))}
function startStreams(){const url='wss://fstream.binance.com/stream?streams=btcusdt@aggTrade/!forceOrder@arr';let ws;const connect=()=>{ws=new WebSocket(url);ws.on('open',()=>{wsState.connected=true;wsState.lastMessage=Date.now()});ws.on('message',raw=>{wsState.lastMessage=Date.now();try{const m=JSON.parse(raw.toString()),d=m.data;if(m.stream==='!forceOrder@arr'&&d?.o){const o=d.o;addLiq(o.S==='SELL'?'LONG':'SHORT',Math.abs(+o.ap*+o.q))}else if(m.stream==='btcusdt@aggTrade'&&d)addLarge(d.m?'SELL':'BUY',Math.abs(+d.p*+d.q))}catch{}});ws.on('close',()=>{wsState.connected=false;wsState.reconnects++;setTimeout(connect,3000)});ws.on('error',()=>{try{ws.close()}catch{}})};connect()};startStreams();
app.get('/api/health',(q,r)=>r.json({ok:true,version:'V4.0.0',time:new Date().toISOString(),stream:wsState}));
app.get('/api/dashboard',async(q,res)=>{try{const [ticker,oi,fun,fg,t5,t15,ls,etf,markets,news,flow]=await Promise.all([getJson(SPOT,'/api/v3/ticker/24hr?symbol=BTCUSDT'),currentOI(),funding(),fearGreed(),tfTech('5m'),tfTech('15m'),longShort(),getETF(),getMarkets(),getNews(),getFlowStats()]);snapshotOI(oi.usd);const ch={1:changeSince(6e4),5:changeSince(5*6e4),10:changeSince(10*6e4),30:changeSince(30*6e4),60:changeSince(36e5),1440:changeSince(864e5)},liq=liqSummary(),large=largeSummary(),sig=signal(t5,t15,ch[5],fun.rate,fg?+fg.value:null,liq,large,etf,markets);const newsLinks=[{name:'Forex Factory',url:'https://www.forexfactory.com/'},{name:'Investing.com',url:'https://www.investing.com/'},{name:'Farside BTC ETF',url:'https://farside.co.uk/btc/'},{name:'Alternative.me',url:'https://alternative.me/crypto/fear-and-greed-index/'}];res.json({timestamp:Date.now(),price:+ticker.lastPrice,change:+ticker.priceChangePercent,volume24h:+ticker.quoteVolume,fearGreed:fg?{value:+fg.value,classification:fg.value_classification}:null,technical:t5,technical15:t15,oi:[['1m',ch[1]],['5m',ch[5]],['10m',ch[10]],['30m',ch[30]],['1H',ch[60]],['1D',ch[1440]]].map(x=>({tf:x[0],oi:oi.usd,change:x[1]})),liquidation:liq,funding:fun,longShort:ls,largeTrade:large,etf,markets,sessions:sessionStatus(),news,sourceLinks:newsLinks,signal:sig,stream:wsState,sources:[['Binance Spot','LIVE'],['Binance Futures','LIVE'],['Binance Liquidation WS',wsState.connected?'LIVE':'RECONNECTING'],['Binance Large Trade Proxy',wsState.connected?'LIVE':'RECONNECTING'],['TradingView','LIVE chart'],['Alternative.me','LIVE'],['Farside','LIVE/DAILY'],['Yahoo Finance public chart','LIVE indices'],['CoinDesk/Cointelegraph RSS','LIVE context'],['Forex Factory / Investing.com','LINKED SOURCE — no scraping']].map(x=>({name:x[0],status:x[1]}))})}catch(e){res.status(503).json({error:e.message})}});
app.use((req,res)=>res.sendFile(path.join(__dirname,'frontend/index.html'))); app.listen(PORT,HOST,()=>console.log(`BTC AI SCALPING ENGINE V4 running on http://${HOST}:${PORT}`));
